---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migcontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migcontrollers/status
  verbs:
  - get
  - patch
  - update
