apiVersion: migrations.kubevirt.io/v1alpha1
kind: MigController
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-migration-operator
    app.kubernetes.io/managed-by: kustomize
  name: migcontroller-sample
  namespace: kubevirt-migration-system
spec:
  # TODO(user): Add fields here
